### ISSUE TITLE
try to install impacket but hit error

### ISSUE THREAD

**Issue by pcodetry** [SecureAuthCorp/impacket#964] opened 2020-09-29 12:05 UTC
### Configuration  
impacket version:  latest
Python version:  3.6.8
Target OS:  Kali 2019
Error: Error: ldap3 2.8.1 has requirement pyasn1>=0.4.6, but you 'll have pyasn1 0.4.2 which is incompatible
hw to resolve

### Debug Output With Command String  
i.e.  
smbexec -debug domain/user:password@127.0.0.1  
```
smbexec -debug domain/user:password@127.0.0.1
[+] StringBinding ncacn_np:127.0.0.1[\pipe\svcctl]
[+] Executing %COMSPEC% /Q /c echo cd  ^> \\127.0.0.1\C$\__output 2^>^&1 > %TEMP%\execute.bat & %COMSPEC% /Q /c %TEMP%\execute.bat & del %TEMP%\execute.bat
[!] Launching semi-interactive shell - Careful what you execute
C:\Windows\system32>net group
[+] Executing %COMSPEC% /Q /c echo net group ^> \\127.0.0.1\C$\__output 2^>^&1 > %TEMP%\execute.bat & %COMSPEC% /Q /c %TEMP%\execute.bat & del %TEMP%\execute.bat
Traceback (most recent call last):
  File "/usr/lib64/python3.7/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'RemoteShell' object has no attribute 'do_net'
```

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
Space for additional context, investigative results, suspected issue.

**Comment by asolino** [comment] 2020-09-29 18:14
Hey @pcodetry

I cannot reproduce this bug. Can you post the whole output, including the impacket banner message?

**Comment by asolino** [comment] 2020-11-05 14:09
No answer, closing.

**Closed by asolino** 2020-11-05 14:09 UTC
