### ISSUE TITLE
smbserver.py : SyntaxError

### ISSUE THREAD

**Issue by 3isenHeiM** [SecureAuthCorp/impacket#1038] opened 2021-03-15 10:06 UTC
### Configuration  
impacket version:  latest 
Python version:  3.9.2
Target OS:  Kali 2021.1

### Debug Output With Command String  
smbserver.py TEST /folder/ -debug

```
smbserver.py TEST /folder/ -debug
Traceback (most recent call last):
  File "/usr/local/bin/smbserver.py", line 19, in <module>
    from impacket import smbserver, version
  File "/usr/local/lib/python3.9/dist-packages/impacket/smbserver.py", line 84
    except Exception, e:
                    ^
SyntaxError: invalid syntax

```

Impacket has been installed in a venv.

**Comment by 0xdeaddood** [comment] 2021-04-21 14:01
Hi @3isenHeiM. I can't reproduce it. Are you sure you are using the latest version of impacket? Seems like an old bug before porting to Python3.

**Comment by 0xdeaddood** [comment] 2021-04-28 15:49
No answer, closing. Reopen if needed.

**Closed by 0xdeaddood** 2021-04-28 15:49 UTC
