### ISSUE TITLE
OpenSSL.SSL.Error: [('SSL routines', '', 'internal error')] in mssqlclient.py

### ISSUE THREAD

**Issue by CT-H00K** [SecureAuthCorp/impacket#1357] opened 2022-06-24 05:05 UTC
### Configuration  
impacket version:  0.10.0
Python version:  3.10
Target OS:  Microsoft SQL Server 2014 12.00.2000

### Debug Output With Command String  
mssqlclient.py -debug domain/user:password@127.0.0.1 -windows-auth 
```
Traceback (most recent call last):
  File "/root/impacket_current/examples/mssqlclient.py", line 175, in <module>
    res = ms_sql.login(options.db, username, password, domain, options.hashes, options.windows_auth)
  File "/root/impacket_current/impacket/tds.py", line 888, in login
    tls.do_handshake()
  File "/root/.local/share/virtualenvs/impacket_current-DVyAu5JV/lib/python3.10/site-packages/OpenSSL/SSL.py", line 1991, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/root/.local/share/virtualenvs/impacket_current-DVyAu5JV/lib/python3.10/site-packages/OpenSSL/SSL.py", line 1700, in _raise_ssl_error
    _raise_current_error()
  File "/root/.local/share/virtualenvs/impacket_current-DVyAu5JV/lib/python3.10/site-packages/OpenSSL/_util.py", line 55, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', '', 'internal error')]
[-] [('SSL routines', '', 'internal error')]
```

I got the previous error when trying to connect to a SQL server. I want to note that I was able to fix the error by providing all ciphers and setting security mode to 0. 
The following lines need to be changed:
https://github.com/SecureAuthCorp/impacket/blob/ac35841f0288aabdfa9fb51f6bb6d83ce2618d2d/impacket/tds.py#L666
https://github.com/SecureAuthCorp/impacket/blob/ac35841f0288aabdfa9fb51f6bb6d83ce2618d2d/impacket/tds.py#L875

And for relaying to work: 
https://github.com/SecureAuthCorp/impacket/blob/ac35841f0288aabdfa9fb51f6bb6d83ce2618d2d/impacket/examples/ntlmrelayx/clients/mssqlrelayclient.py#L53

I changed the following line: 

```
ctx = SSL.Context(SSL.TLSv1_METHOD)
ctx.set_cipher_list('RC4, AES256')
```
 to

```
ctx = SSL.Context(SSL.TLS_METHOD)
ctx.set_cipher_list('ALL:@SECLEVEL=0'.encode('utf-8'))
```

According to the documentation set_cipher_list requires a byte array in the format of: 
https://www.openssl.org/docs/man1.1.1/man1/ciphers.html
https://www.pyopenssl.org/en/stable/api/ssl.html#OpenSSL.SSL.Context.set_cipher_list

Also new code should use SSL.TLS_METHOD as stated here:
https://www.pyopenssl.org/en/stable/api/ssl.html#OpenSSL.SSL.TLSv1_2_METHOD

**Comment by 0xdeaddood** [comment] 2022-06-24 17:09
Hi @CT-H00K!

Thanks for the report. This is a duplicate of https://github.com/SecureAuthCorp/impacket/issues/856. Also, there is an open PR https://github.com/SecureAuthCorp/impacket/pull/1356 to fix it. Lets continue the discussion there.

**Closed by 0xdeaddood** 2022-06-24 17:09 UTC
Labels: duplicate
