### ISSUE TITLE
ntlmrelayx: socket ssl wrapping error

### ISSUE THREAD

**Issue by dtrizna** [SecureAuthCorp/impacket#581] opened 2019-03-07 15:12 UTC
Hi! 

I'm facing the issue when using relay for LDAPs traffic.
Whole exception with `-debug` flug:

`[-] Exception in HTTP request handler: ('unable to open socket', [(LDAPSocketOpenError('socket ssl wrapping error: [Errno 104] Connection reset by peer',), ('A.B.C.D', 636))])
[+] Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 72, in handle_one_request
    SimpleHTTPServer.SimpleHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 193, in do_GET
    if not self.do_ntlm_negotiate(token, proxy=proxy):
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/servers/httprelayserver.py", line 261, in do_ntlm_negotiate
    if not self.client.initConnection():
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/clients/ldaprelayclient.py", line 144, in initConnection
    self.session.open(False)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/base.py", line 147, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
LDAPSocketOpenError: ('unable to open socket', [(LDAPSocketOpenError('socket ssl wrapping error: [Errno 104] Connection reset by peer',), ('A.B.C.D', 636))])`

System:
- Python 2.7.15+
- up to date Kali
- up to date impacket
- ldap3 tested both 2.5.1 and 2.5.2

Same problem was slightly touched in #514, where @dirkjanm mentioned:

> (..) it has something to do with whether the SSL certificates are set correctly on the server. Usually targeting another DC worked

I have access to ~12 AD systems (2012 R2 and 2016), targeting any of them results into this error.
Connections using ldp.exe works well (along with many production calls to some of ADs):
![image](https://user-images.githubusercontent.com/15322061/53963138-53e20f80-40f5-11e9-8c95-834186eb2bda.png)

LDAP signing not enabled:
![image](https://user-images.githubusercontent.com/15322061/53963405-ed112600-40f5-11e9-8d00-2862831bb1a4.png)

Behavior is that LDAPs service RST connection just after TLS hello is received:
![image](https://user-images.githubusercontent.com/15322061/53963519-25186900-40f6-11e9-8f12-898d866f3db8.png)

So this is not caused by ntlmrelayx not trusting LDAPs sertificate - it's about LDAPs refusing this TLS hello packet.

Any ideas?

**Comment by dtrizna** [comment] 2019-03-07 15:12
Before requesting this issue I've

One key difference I noticed between request made by ldap3 and by f.e. ldp.exe, is timestamp here and TLS version here:
![image](https://user-images.githubusercontent.com/15322061/53965686-57c46080-40fa-11e9-919f-089692265210.png)
This is screen from failed TLS hello message. Valid authentication uses TLSv1.2 and correct timestamp, whilst ntlmrelayx generates for every TLS session kinda random starting from year 1996 up to 2072.

I've tried to investigate where this settings can be tuned, by modifying some aspects of this Class https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/clients/ldaprelayclient.py#L141 with no success.

**Comment by dirkjanm** [comment] 2019-03-07 18:48
Good analysis! I can't reproduce it locally (maybe i'd have to play with which ciphers are accepted by the DC) but the TLS logic of LDAP3 is here:
https://github.com/cannatag/ldap3/blob/master/ldap3/core/tls.py
Maybe it will help you in the right direction.

**Comment by dirkjanm** [comment] 2019-03-07 21:15
Can you check what the `algorithmIdentifier` is that your server is sending when you connect with ldp.exe? Reading around a bit suggests this could be a certificate signing option that is not supported by your version of openssl/python.

**Comment by dtrizna** [comment] 2019-03-08 10:34
Hi, @dirkjanm!
Thanks for reference to tls logics, will try to find a way to tune timestamp there.

I see `algorithmIdentifier` under the server's certificate, is that right?
It's `Algorithm Id: 1.2.840.113549.1.1.11 (sha256WithRSAEncryption)`

Any ideas about that?

**Comment by hausec** [comment] 2019-03-08 20:17
Also having this issue. I'm able to connect via ldp.exe over 636, however get a 104 reset from ntlmrelayx. Looking on the DC event log shows two relevant alerts:

- A fatal alert was generated and sent to the remote endpoint. This may result in termination of the connection. The TLS protocol defined fatal error code is 40. The Windows SChannel error state is 1205.

- An TLS 1.2 connection request was received from a remote client application, but none of the cipher suites supported by the client application are supported by the server. The SSL connection request has failed.

**Comment by dirkjanm** [comment] 2019-03-09 10:01
If anyone can look what ciphers the python client supports (in the Client Hello package) and what the server offers (in the Server Hello of the working ldp.exe) I can try to replicate it and maybe figure out if this is purely related to openssl or with how python interacts with it.

**Comment by hausec** [comment] 2019-03-09 21:19
So this is definitely just related to Kali. It works fine on Ubuntu 18 & 16.

**Comment by dirkjanm** [comment] 2019-03-10 10:34
>     * Then of course, getST.py doesn't work with Ubuntu out of the box but does with Kali. Didn't really feel like trouble shooting but I was getting
>       [Errno Connection error (LAB.LOCAL:88)] [Errno -2] Name or service not known. Separate issue though, I'll open another issue if I can't get it working.

That sounds like avahi messing up resolving for .local domains.
`apt-get purge avahi-daemon` to fix

**Comment by dtrizna** [comment] 2019-03-11 07:45
@hausec , unfortunately for me with Ubuntu 18.04.2 situation is the same:
![image](https://user-images.githubusercontent.com/15322061/54107552-30afac80-43e2-11e9-9036-be3d1f929f2a.png)
Will try to dig deeper on cipher question after a while.

**Comment by xianyuzailushang** [comment] 2019-03-11 10:30
![image](https://user-images.githubusercontent.com/20908868/54117367-8bb9c180-442b-11e9-9f52-c60a45bb7e1f.png)
ubuntu 16.04
windows server 2012
Also encountered this problem

**Comment by dirkjanm** [comment] 2019-03-12 21:10
If anyone could share a PCAP of this error **and** also include how a working connection (using for example `ldp.exe` on Windows) looks, it would be very useful for debugging this.

**Comment by l3m0n** [comment] 2019-03-13 02:40
> ubuntu 18.04
> windows 2008 r2
> 
> ![upload_0534c48fadf02769c5fbdc02c7e474d3](https://user-images.githubusercontent.com/10672574/54181467-9763c180-44d9-11e9-9634-2d19440d68ba.png)

I solved the problem, Because I forgot to open ladps over SSL. 

[Enable LDAP over SSL (LDAPS) for Microsoft Active Directory servers](https://gist.github.com/magnetikonline/0ccdabfec58eb1929c997d22e7341e45)

Finally, I succeeded on Windows 2012 and Windows 7.
Thank you.

**Comment by stathisb** [comment] 2019-03-13 08:58
The solution that was posted by @l3m0n also worked for me!  It seems that the LDAP over SSL was not enabled/properly configured in the DC.

**Comment by asolino** [comment] 2019-03-15 16:45
Is the solution proposed by @l3m0n working for you all? What about @dtrizna?

**Comment by dtrizna** [comment] 2019-03-19 09:19
Hi @asolino!

Sorry for late answer!
@l3m0n described a bit different situation, simply ntlmrelayx exception was the same.
In that case problem was with LDAPS setup initially - SSL/TLS there didn't worked at all as I understand.

Unfortunately this does not apply to initial description, here is the case with some prod servers as well that run LDAPS successfully in field (which was confirmed with ldp.exe over SSL in initial post)...

Still looks as case of TLS values problem in ntlmrelayx's Hello packet. 
I can confirm that TLS ciphers are overlapping in failed and successful Hello packet, so this shouldn't be the case. 
Presumably the key thing is that there's random time in ntlmrelayx's TLS Client Hello packet that is discarded by our LDAP (good boy, ldap!). I see that both on Kali and Ubuntu 18.04 so assume that it's tool, not environment specific:

![image](https://user-images.githubusercontent.com/15322061/54593984-5703c680-4a38-11e9-97da-ffb16e77c01f.png)

Hope to find some time to dig further and tune ldap3 TLS time settings. Not sure when though.
If anyone here can verify why time in ntlmrelayx's Hello packet is incorrect - it would be useful.

**Comment by T3KX** [comment] 2019-06-09 01:54
I am experiencing the same thing here 
Kali 2019.2 , impacket V0.9.20-dev

I can confirm that it was working on impacket v0.19 , on the same  DC

**Comment by skorov** [comment] 2019-06-27 12:45
I did some experimenting with this bug tonight. I get the same results as a lot of people in this thread: Error relaying to LDAPS on a brand new DC.
What "fixed" it for me, was adding the CA role to the DC. This creates a certificate for the LDAPS server to use (after restarting the server).

@dirkjanm: In your lab, did you setup your DC to be a CA? If so, that might explain why it works in your lab but not others.

I guess what I'm still unsure about is how I can join other servers to the domain without a working LDAPS server... Correct me if I'm wrong, but isn't LDAPS required to add computer accounts to the DC?

**Comment by dirkjanm** [comment] 2019-06-27 13:41
Yes you do need to have a valid certificate to use LDAPS, which gets automatically added when you add the CA role to the DC. Otherwise LDAPS will not work and will immediately reset the connection (both with impacket and with ldp.exe).
As far as I know, Windows does not use LDAPS for anything, it uses plain LDAP with integrity, which means traffic is encrypted with GSSAPI.

**Comment by skorov** [comment] 2019-06-27 21:57
That makes sense. Wouldn't it then be possible to get ntlmrelayx to do the same thing? Using LDAP with integrity for the --add-computer switch?

**Comment by dirkjanm** [comment] 2019-06-27 22:06
It is but the encryption key for this is derived from (I think) the encrypted session key which is encrypted based on the password during authentication, so you don't have this key if you're relaying. I'd have to look up the exact details. With LDAPs the encryption is done separate from the authentication so this isn't a problem when relaying, but it isn't always configured.

**Comment by mpgn** [comment] 2020-01-29 15:39
Hell @dirkjanm 

I did a bit of debugging because I had same error has everyone :

```
[-] Connection against target ldaps://demo.local FAILED: ('unable to open socket', [(LDAPSocketOpenError('socket ssl wrapping error: [Errno 104] Connection reset by peer',), ('172.16.60.205', 636))])
```

What I found is that the problem is not related to `impacket` but the `openssl` version installed in Kali.

Let's check:

**Kali testing**, I check if LDAPS is working:
```
root@kali:~# curl -vk ldaps://demo.local 
*   Trying 172.16.60.205:636...
* TCP_NODELAY set
* Connected to demo.local (172.16.60.205) port 636 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to demo.local:636 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to demo.local:636 

root@kali:~# openssl
OpenSSL> version
OpenSSL 1.1.1d  10 Sep 2019
OpenSSL> exit
```
Maybe related to openssl version installed in Kali ? https://github.com/openssl/openssl/issues/9566#issuecomment-522712843

I've tested on my laptop with an older version of openssl =>
```
⋊> ~/T/ on master ⨯ openssl                                                                          
OpenSSL> version
OpenSSL 1.1.1  11 Sep 2018
OpenSSL> 
```
And this is where the magic is => 

```
⋊> ~/T/Responder on master ⨯ curl -k ldaps://demo.local                                                       
* Rebuilt URL to: ldaps://demo.local/
*   Trying 172.16.60.205...
* TCP_NODELAY set
* Connected to demo.local (172.16.60.205) port 636 (#0)
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA384
* Server certificate:
*  subject: CN=DEMO-DC.demo.local
*  start date: Jan 29 13:45:50 2020 GMT
*  expire date: Jan 28 13:45:50 2021 GMT
*  issuer: DC=local; DC=demo; CN=demo-DEMO-DC-CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* LDAP local: ldaps://demo.local/
DN: 
	currentTime: 20200129152203.0Z

	subschemaSubentry: CN=Aggregate,CN=Schema,CN=Configuration,DC=demo,DC=local


```

With an older version of openssl I can use the LDAPS service of my AD. Did `ntlmrelayx` with ldaps was working on my local computer, YES !

---

How did I generate my certificate ? Well I've just use the Active Directory Certificates Services and clikc Next Next Next all the time without touching anything.

![image](https://user-images.githubusercontent.com/5891788/73370011-d64a6380-42b3-11ea-9851-3f3a1df75c92.png)

Then I simply restart the AD and check if the certificat was on the Personal Certificat (local computer)

![image](https://user-images.githubusercontent.com/5891788/73370131-02fe7b00-42b4-11ea-9849-faab40a312d6.png)

Then using LDP.exe I was able to connect to the LDAS service on port 636

![image](https://user-images.githubusercontent.com/5891788/73370211-25909400-42b4-11ea-96c6-189ed1108473.png)

But using Kali, I cannot connect to LDAPS with openssl v1.1.1d (sep 2019)  but only with openssl 1.11.1 (sep 2018)

Hope it help ! :)

**Comment by 0xdeaddood** [comment] 2020-01-31 22:32
Great explanation @mpgn. I had the same issue and resolved it downgrading the version of OpenSSL from 1.1.1c  (May 2019) to 1.1.1 (Sep 2018).

**Comment by sateng** [comment] 2020-02-16 12:03
How did you accomplish the downgrade without destroying all dependencies? I have same issue with ntlmrelayx (even after upgrade to version 3)

**Comment by mpgn** [comment] 2020-02-16 14:56
Nice catch @sateng ! looks better than downgrading openssl 💯

**Comment by moj0-bf** [comment] 2020-02-26 15:31
Man - I ran into this same thing on another project and it completely slipped my mind while troubleshooting this one! Thank you @sateng !

**Comment by mpgn** [comment] 2020-04-16 14:25
Hello @asolino I think you can close this issue :)

**Closed** 2020-04-16 14:35 UTC

**Comment by n00py** [comment] 2022-02-18 17:34
> 



> Nice catch @sateng ! looks better than downgrading openssl 💯

Is there a deleted comment here? I really was enjoying this thread and then the solution seems to be missing
