### ISSUE TITLE
longname is only the first character of the name when listing files in a share

### ISSUE THREAD

**Issue by lasalvavida** [SecureAuthCorp/impacket#545] opened 2018-12-13 20:13 UTC
Using `impacket.smbserver.SimpleSMBServer` as the server and `impacket.smbconnection.SMBConnection` as the client.

```python
for f in smb.listPath(share, '*'):
        print f
        name = f.get_longname()
        print name
```

Output (impacket 0.9.15)
```
<SharedFile instance: shortname="", longname=".", filesize=4096>
.
<SharedFile instance: shortname="", longname="..", filesize=4096>
..
<SharedFile instance: shortname="", longname="firmware", filesize=4096>
firmware
<SharedFile instance: shortname="", longname="README.md", filesize=920>
README.md
```

Output (impacket 0.9.17)
```
<SharedFile instance: shortname="", longname=".", filesize=4096>
.
<SharedFile instance: shortname="", longname=".", filesize=4096>
.
<SharedFile instance: shortname="", longname="f", filesize=4096>
f
<SharedFile instance: shortname="", longname="R", filesize=920>
R
```
Issue is still present in impacket 0.9.18.

**Comment by asolino** [comment] 2018-12-13 21:16
Thanks for the report @lasalvavida 

What OS are you running this under? Can't reproduce it on macOS (although I can in the `python36` branch).
This also shouldn't happen if you run `smbserver.py` with the `smb2support` switch. Please let me know if that's true on your side.

**Comment by lasalvavida** [comment] 2018-12-13 21:49
> What OS are you running this under?

I am using Linux.

OS info:
```bash
lsb_release -a
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 5.0 Juno
Release:	5.0
Codename:	juno
```

```
uname -r
4.15.0-42-generic
```

> This also shouldn't happen if you run smbserver.py with the smb2support switch. Please let me know if that's true on your side.

SMB2 support is currently disabled - the other client (not impacket) that uses this server doesn't support it. If I enable SMB2, the issue is not present using the impacket client.

**Comment by asolino** [comment] 2018-12-15 01:32
Thanks @lasalvavida 

Please run inside a Python interpreter the following:
```Python
import sys
sys.getfilesystemencoding()
```
and send me the output.

>  the other client (not impacket) that uses this server doesn't support it. 

Are you having the same issue with that client as well?

> If I enable SMB2, the issue is not present using the impacket client in 0.9.18

Thanks for checking.

**Comment by asolino** [comment] 2018-12-15 13:58
Hey @lasalvavida 

Please re-test with the latest commits

**Comment by lasalvavida** [comment] 2018-12-19 19:13
```python
>>> sys.getfilesystemencoding()
'UTF-8'
```

> Are you having the same issue with that client as well?

Yes

**Comment by lasalvavida** [comment] 2018-12-19 19:18
> Please re-test with the latest commits

I get an exception on `listPath`.

> Traceback (most recent call last):
  File "tools/generate_config.py", line 138, in <module>
    for f in smb.listPath(share, '*'):
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbconnection.py", line 422, in listPath
    raise SessionError(e.get_error_code(), e.get_error_packet())
impacket.smbconnection.SessionError: SMB SessionError: STATUS_OBJECT_PATH_NOT_FOUND({Path Not Found} The path %hs does not exist.)

**Comment by asolino** [comment] 2018-12-20 00:44
What is the target OS you are trying to connect?

**Comment by lasalvavida** [comment] 2018-12-20 03:52
> What is the target OS you are trying to connect?

What do you mean? Client and server are running on the same machine.

**Comment by asolino** [comment] 2018-12-20 12:31
> What do you mean? Client and server are running on the same machine.

Nevermind, got confused with another ticket :/

Ok.. after applying https://github.com/SecureAuthCorp/impacket/commit/f99aaf93d02b9da5f1219e083f82f4c722b0ace7 I cannot reproduce this anymore.

The `STATUS_OBJECT_PATH_NOT_FOUND` is probably happening because you're specifying the wrong `share`. Have in mind the share name *is* case sensitive. 

My test was (latest `master` branch running on Kali Linux):
1. Run `smbserver.py`:
```
./smbserver.py tmp /root/src/impacket/tests/
Impacket v0.9.19-dev - Copyright 2018 SecureAuth Corporation

[*] Config file parsed
[*] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
[*] Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
[*] Config file parsed
[*] Config file parsed
[*] Config file parsed
```
2. Connect client 
```
Python 2.7.14 (default, Sep 17 2017, 18:50:44) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from impacket.smbconnection import SMBConnection
>>> s = SMBConnection('127.0.0.1', '127.0.0.1')
>>> s.login('test', 'test')
>>> for f in s.listPath('tmp', '*'):
...     print f
...     print f.get_longname()
... 
<SharedFile instance: shortname="", longname=".", filesize=4096>
.
<SharedFile instance: shortname="", longname="..", filesize=4096>
..
<SharedFile instance: shortname="", longname="misc", filesize=4096>
misc
<SharedFile instance: shortname="", longname="ImpactPacket", filesize=4096>
ImpactPacket
<SharedFile instance: shortname="", longname="walkmodules.py", filesize=568>
walkmodules.py
<SharedFile instance: shortname="", longname="SMB_RPC", filesize=4096>
SMB_RPC
<SharedFile instance: shortname="", longname="dot11", filesize=4096>
dot11
<SharedFile instance: shortname="", longname="runall.sh", filesize=2652>
runall.sh
>>> 
```

**Comment by lasalvavida** [comment] 2018-12-21 15:54
> The STATUS_OBJECT_PATH_NOT_FOUND is probably happening because you're specifying the wrong share. Have in mind the share name is case sensitive.

I am getting the share name directly from the `SMBConnection` using `listShares`, and it does look correct.

Here is my server script:

```python
server = smbserver.SimpleSMBServer()
server.addShare('images', '.')
server.setSMB2Support(False)
print('Server running...')
server.start()
```

This was working before, so it seems like maybe a (possibly unrelated) regression in master.

**Comment by asolino** [comment] 2018-12-21 22:04
> This was working before, so it seems like maybe a (possibly unrelated) regression in master.

Keep in mind `listPath()` is returning a `NULL` terminated sharename (following https://msdn.microsoft.com/en-us/library/cc247147.aspx). 

```
>>> s = SMBConnection('127.0.0.1', '127.0.0.1')
>>> s.login('test', 'test')
>>> s.listShares()[0].dump()
SHARE_INFO_1 
shi1_netname:                    u'TMP\x00' 
shi1_type:                       0 
shi1_remark:                     u'\x00'
```

Please re-test having this in mind.

**Comment by asolino** [comment] 2019-01-07 15:32
Hey @lasalvavida 

> I'm not following you here, so maybe I need to be clearer

What I'm saying is we're now following more accurate the Microsoft documentation about SMB Share structures. In particular: 

> shi1_netname: A pointer to a null-terminated Unicode UTF-16 string that specifies the name of a shared resource. The server MUST ignore this member when processing the NetrShareSetInfo (section 3.1.4.11) method.

Meaning, shares received now have a trailing '\x00' at the end. When you ask for a share using `listPath` you need to specify a shareName, with no '\x00' at the end of it. If you leave the '\x00' it might still work tho, but you're sending an extra character to the server.

Your server code needs a small change:
```Python
server.addShare('images'.upper(), '.')
```

Change your client code to this and re-test:
```Python
smb = SMBConnection(address, address, sess_port=445, timeout=1)
smb.login('', '', '')
shareNames = []
for share in smb.listShares():
    shareName = share['shi1_netname']
    if shareName != 'IPC$\x00':
        shareNames.append(shareName)

if len(shareNames) == 0:
    print('No hosted shares found.')
share = shareNames[0][:-1]

for f in smb.listPath(share, '*'):
    print(f)
    name = f.get_longname()
    print(name)
```

> This exact code works correctly on impacket 0.9.15.

There were many changes since 0.9.15, in particular with the RPC runtime, aiming at making it closer to the actual Microsoft Protocol Standards. Don't expect everything working on `0.9.15` working on the latest versions.

> This happens even if I call smb.listPath('images', '*'), so pretty clearly something is still wrong here.

Try with `'images'.upper()`. I will enforce this inside `addShare()` in order to avoid this confusion.

Please re-test everything and let me know if it works on your side.

**Comment by 0xdeaddood** [comment] 2021-04-21 17:06
No answer, closing.

**Closed by 0xdeaddood** 2021-04-21 17:06 UTC
