### ISSUE TITLE
GetADUsers.py - TypeError: init() takes no arguments

### ISSUE THREAD

**Issue by Chaplin-Sec** [SecureAuthCorp/impacket#763] opened 2020-02-05 17:36 UTC
I keep getting errors when trying to run GetADUsers.py against a box.

I am typing the following in my terminal:

`./GetADUsers.py -all domain\useraccount:password -dc-ip 1.1.1.1`

and

`./GetADUsers.py -all domain\user -dc-ip 1.1.1.1`

I receive the following output:

`Traceback (most recent call last):
     File "./GetADUsers.py", line 213, in <module>
     logger.init(options.ts)
TypeError: init() takes no arguments (1 given)
`

I have triple checked the documentation and seen others use it on blogs and videos but my script fails to work and I have no idea why, am I being idiot or is there something wrong with the tool?

I am currently running Kali 2020.1

**Comment by asolino** [comment] 2020-02-05 17:40
Duplicate of https://github.com/SecureAuthCorp/impacket/issues/754

**Closed by asolino** 2020-02-05 17:40 UTC

**Comment by Chaplin-Sec** [comment] 2020-02-05 17:43
Damn, sorry about that, I tried to find a  post about this.

I will check it out.

**Comment by asolino** [comment] 2020-02-05 17:44
No worries!. Let me know if you can't solve the issue. Should be simple.

**Comment by Chaplin-Sec** [comment] 2020-02-05 18:31
Yeah I was able to solve it. Thank you very much.

Due to the other scripts working fine I assumed no installation was required. I didn't read the repo information either, it was as clear as day that I had to install the packages, lol.

Feeling a little daft at the minute.

**Comment by asolino** [comment] 2020-02-05 18:41
Great to know you solve it.. Not Daft at all.. happened to all of us once.. Cheers.
