### ISSUE TITLE
logger.init(options.ts) : init() takes no arguments

### ISSUE THREAD

**Issue by thomaslc66** [SecureAuthCorp/impacket#756] opened 2020-01-25 23:55 UTC
### Configuration  
impacket version:  
Python version:  
Target OS:  

### Debug Output With Command String  
i.e.  
samrdump 127.0.0.1
// and all other script with this logger.init() line  
```
Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation

Traceback (most recent call last):
  File "samrdump.py", line 234, in <module>
    logger.init(options.ts)
TypeError: init() takes no arguments (1 given)

```

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
Space for additional context, investigative results, suspected issue.

**Comment by asolino** [comment] 2020-01-26 13:50
You don't have the latest master branch installed. Be sure to `git pull`
and install properly. Report back on the result please.

**Comment by asolino** [comment] 2020-01-26 17:21
Duplicate of https://github.com/SecureAuthCorp/impacket/issues/754, continue discussion there. Closing.

**Closed by asolino** 2020-01-26 17:21 UTC
