### ISSUE TITLE
NTDS decryption does not occur.

### ISSUE THREAD

**Issue by Anton19780301** [SecureAuthCorp/impacket#659] opened 2019-07-31 17:32 UTC
root@home:/home/anton/impacket/examples# python secretsdump.py -ntds //home/anton/NTDS/ntds.dit -system //home/anton/NTDS/system.save LOCAL
Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation

[*] Target system bootKey: 0xae847e0aec52544e752c8f9be273bc36
[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Searching for pekList, be patient
[*] Reading and decrypting hashes from //home/anton/NTDS/ntds.dit 
[*] Cleaning up... 
 

And nothing....

The most amazing thing is that I am stitching the base for the second time and for the first time it turned.

What could have happened?

**Comment by asolino** [comment] 2019-07-31 18:14
No pek found.. probably a corrupted DIT file or system hive.

Don't understand your second statement.

**Comment by Anton19780301** [comment] 2019-07-31 18:46
I am sorry, I use Google translator.
I meant that earlier I managed to decipher the base. But I already understood what was wrong. Before decoding, you need to repair the database using Ntdsutil.

**Comment by asolino** [comment] 2019-07-31 19:00
Good to know the issue is solved. Closing.

**Closed by asolino** 2019-07-31 19:00 UTC
