### ISSUE TITLE
UTF encoding issues with ntlmrelayx

### ISSUE THREAD

**Issue by tfriesen** [SecureAuthCorp/impacket#586] opened 2019-03-11 21:25 UTC
I'm having some issues running the trunk version of ntlmrelayx. They seem to be related to UTF encoding (some of my own debugging info included)

```
[*] Authenticating against ldaps://10.X.X.X as \晴楲獥湥 SUCCEED
[*] Enumerating relayed user's privileges. This may take a while on large domains
('Username: ', u'\u6674\u6972\u7365\u6e65') \\result of print(username)
[] \\result of print(self.client.entries)
ldaps://10.x.x.x:636 - ssl - user: a - not lazy - bound - open - <local: 10.x.x.166:50564 - remote: 10.x.x.x:636> - tls not started - listening - SyncStrategy - internal decoder \\result of print(self.client)
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 495, in run
    userSid, privs = self.validatePrivileges(self.username, domainDumper)
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 322, in validatePrivileges
    user = self.client.entries[0]
IndexError: list index out of range
```

When converted back to utf8, that utf16 string decodes as my username (tfriesen).

Trying a different account, I get

```
[*] HTTPD: Received connection from 10.x.x.166, attacking target ldaps://10.x.x.x
[*] HTTPD: Client requested path: /
[*] HTTPD: Client requested path: /
[*] HTTPD: Client requested path: /
[-] Exception in HTTP request handler: 'utf16' codec can't decode byte 0x72 in position 12: truncated data
```
 
Suggesting it is an odd number of bytes, and therefore can't be decoded as utf16.

This happened on a relatively clean install of Kali 64 bit, up-to-date. Python 2.7.16rc1.

**Comment by tfriesen** [comment] 2019-03-11 21:53
Upon further investigation, this seems to be a problem with the HTTP Request server, and specifically, when wget is the HTTP client. Not sure why that should be.

**Comment by asolino** [comment] 2019-05-15 17:57
Is there any way I can reproduce this issue? Please try to send me some repro steps so I can investigate.

**Comment by tfriesen** [comment] 2019-05-15 19:17
Certainly.

```
$ ntlmrelayx.py  -t ldaps://<target>

$ wget http://<username>:<pass>@<ntlmrelayx host>
```

Yields output:

```
Impacket v0.9.19-dev - Copyright 2019 SecureAuth Corporation

[*] Protocol Client MSSQL loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] HTTPD: Received connection from 10.1.1.166, attacking target ldaps://10.1.1.5
[*] HTTPD: Client requested path: /
[*] HTTPD: Client requested path: /
[*] HTTPD: Client requested path: /
[-] Authenticating against ldaps://10.1.1.5 as \晴楲獥湥 FAILED
...
```

Any username or password will do. I am running a recent version of Kali, with the latest version of code from the trunk.

**Comment by asolino** [comment] 2019-05-15 19:56
Thanks for the extra data @tfriesen 

For some reason, `wget` is setting the `ntlm.NTLMSSP_NEGOTIATE_UNICODE` when sending the `AUTHENTICATE_MESSAGE` but then sending the username in ASCII. We just don't support that use case, actually I don't know if it is valid. That's the reason why you experience this only with wget.

I'm closing this as won't fix since this isn't a valid use case.

**Closed by asolino** 2019-05-15 19:56 UTC
