### ISSUE TITLE
TypeError: 'ConnectionResetError' object is not subscriptable

### ISSUE THREAD

**Issue by pacmanoth** [SecureAuthCorp/impacket#599] opened 2019-04-03 21:12 UTC
Just thought you should know that we're very eagerly anticipating the final release of this library for Python 3!!  About how long do you think you're away from releasing the final 1.0 version?

Here's a bug we found that I thought you'd want to be aware of:

  File "D:\Program Files\Python37\py3_venv\lib\site-packages\impacket-0.9.20.dev0-py3.7.egg\impacket\smbconnection.py", line 403, in listShares
    dce.connect()
  File "D:\Program Files\Python37\py3_venv\lib\site-packages\impacket-0.9.20.dev0-py3.7.egg\impacket\dcerpc\v5\rpcrt.py", line 800, in connect
    return self._transport.connect()
  File "D:\Program Files\Python37\py3_venv\lib\site-packages\impacket-0.9.20.dev0-py3.7.egg\impacket\dcerpc\v5\transport.py", line 399, in connect
    self.__tid = self.__smb_connection.connectTree('IPC$')
  File "D:\Program Files\Python37\py3_venv\lib\site-packages\impacket-0.9.20.dev0-py3.7.egg\impacket\smbconnection.py", line 380, in connectTree
    return self._SMBConnection.connect_tree(share)
  File "D:\Program Files\Python37\py3_venv\lib\site-packages\impacket-0.9.20.dev0-py3.7.egg\impacket\smb3.py", line 857, in connectTree
    packet = self.recvSMB(packetID)
  File "D:\Program Files\Python37\py3_venv\lib\site-packages\impacket-0.9.20.dev0-py3.7.egg\impacket\smb3.py", line 391, in recvSMB
    data = self._NetBIOSSession.recv_packet(self._timeout)
  File "D:\Program Files\Python37\py3_venv\lib\site-packages\impacket-0.9.20.dev0-py3.7.egg\impacket\nmb.py", line 914, in recv_packet
    data = self.__read(timeout)
  File "D:\Program Files\Python37\py3_venv\lib\site-packages\impacket-0.9.20.dev0-py3.7.egg\impacket\nmb.py", line 992, in __read
    data = self.read_function(4, timeout)
  File "D:\Program Files\Python37\py3_venv\lib\site-packages\impacket-0.9.20.dev0-py3.7.egg\impacket\nmb.py", line 986, in non_polling_read
    if ex[0] != errno.EINTR and ex[0] != errno.EAGAIN:
TypeError: 'ConnectionResetError' object is not subscriptable

**Comment by asolino** [comment] 2019-04-03 21:15
Hey @pacmanoth 

No idea about a v1 release.. guess that won't happen until a better documentation is built. 

What are the repro steps for this bug?

**Comment by pacmanoth** [comment] 2019-04-03 21:29
I am using this library to run a remote discovery binary.  That would probably be very hard for you to set up.

However, I can provide the following additional details:
1) Remove windows is Windows 6.3, Build 9600  (Windows Server 2012, R2)
2) SMB protocol is v3.0
3) The remove session was forcibly closed by the remote host.  Here's the error:
CRITICAL | Thread-195   |04-03-19 12:57:47 | WindowsDiscoverer    | Traceback (most recent call last):
  File "D:\Program Files\Python37\py3_venv\lib\site-packages\impacket-0.9.20.dev0-py3.7.egg\impacket\nmb.py", line 979, in non_polling_read
    received = self._sock.recv(bytes_left)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, the exception mentioned at the beginning of this issue occurred.

Hope that helps!

**Comment by pacmanoth** [comment] 2019-04-03 21:29
"remote"

**Comment by pacmanoth** [comment] 2019-04-03 23:27
I have found some more potentially helpful information regarding the ConnectionResetError.  When this error occurs in nmb.py (line 979), the state of objects is:

**exception**
	args	<class 'tuple'>: (10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)	
	characters_written	str: Traceback (most recent call last):\n  File "D:\\Program Files\\Python37\\py3_venv\\lib\\site-packages\\impacket-0.9.20.dev0-py3.7.egg\\impacket\\nmb.py", line 979, in non_polling_read\n    received = self._sock.recv(bytes_left)\nConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "C:\\TransformationManager\\eclipseNeon\\plugins\\org.python.pydev.core_7.0.3.201811082356\\pysrc\\_pydevd_bundle\\pydevd_resolver.py", line 166, in _getPyDictionary\n    attr = getattr(var, n)\nAttributeError: characters_written\n	
	errno	int: 10054	
	filename	NoneType: None	
	filename2	NoneType: None	
	strerror	str: An existing connection was forcibly closed by the remote host	
	winerror	int: 10054	


**self._sock**
socket: <socket.socket fd=1604, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('137.65.56.93', 64399), raddr=('151.155.185.210', 445)>

**ready**
<class 'list'>: [1604]

**read_length**
int: 4

**data**
bytes: b''

**bytes_left**
4

**timeout**
60

**GLOBALS**
'__name__' (5455408)	str: impacket.nmb	
'__doc__' (5440448)	NoneType: None	
'__package__' (5593152)	str: impacket	
'__loader__' (5593192)	zipimporter: <zipimporter object "D:\\Program Files\\Python37\\py3_venv\\lib\\site-packages\\impacket-0.9.20.dev0-py3.7.egg\\impacket\\">	
'__spec__' (5593232)	ModuleSpec: ModuleSpec(name='impacket.nmb', loader=<zipimporter object "D:\\Program Files\\Python37\\py3_venv\\lib\\site-packages\\impacket-0.9.20.dev0-py3.7.egg\\impacket\\">, origin='D:\\\\Program Files\\\\Python37\\\\py3_venv\\\\lib\\\\site-packages\\\\impacket-0.9.20.dev0-py3.7.egg\\\\impacket\\\\nmb.py')	
'__builtins__' (5993000)	dict: {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\\n\\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'breakpoint': <built-in function breakpoint>, 'callable': <built-in function callable>, 'chr': <built-in function chr>, 'compile': <built-in function compile>, 'delattr': <built-in function delattr>, 'dir': <built-in function dir>, 'divmod': <built-in function divmod>, 'eval': <built-in function eval>, 'exec': <built-in function exec>, 'format': <built-in function format>, 'getattr': <b...	
'__file__' (5929304)	str: D:\\Program Files\\Python37\\py3_venv\\lib\\site-packages\\impacket-0.9.20.dev0-py3.7.egg\\impacket\\nmb.py	
'__cached__' (5930784)	NoneType: None	
'division' (39671472)	_Feature: _Feature((2, 2, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 8192)	
'print_function' (39671592)	_Feature: _Feature((2, 6, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 65536)	
'absolute_import' (39671512)	_Feature: _Feature((2, 5, 0, 'alpha', 1), (3, 0, 0, 'alpha', 0), 16384)	
'errno' (5643584)	module: <module 'errno' (built-in)>	
're' (38031104)	module: <module 're' from 'D:\\\\Program Files\\\\Python37\\\\lib\\\\re.py'>	
'select' (38357344)	module: <module 'select' from 'D:\\\\Program Files\\\\Python37\\\\DLLs\\\\select.pyd'>	
'socket' (38357312)	module: <module 'socket' from 'D:\\\\Program Files\\\\Python37\\\\lib\\\\socket.py'>	
'string' (6746432)	module: <module 'string' from 'D:\\\\Program Files\\\\Python37\\\\lib\\\\string.py'>	
'time' (39085728)	module: <module 'time' (built-in)>	
'random' (39435072)	module: <module 'random' from 'D:\\\\Program Files\\\\Python37\\\\lib\\\\random.py'>	
'pack' (39038496)	builtin_function_or_method: <built-in function pack>	
'unpack' (39038144)	builtin_function_or_method: <built-in function unpack>	
'byte2int' (45655368)	itemgetter: operator.itemgetter(0)	
'indexbytes' (45655408)	builtin_function_or_method: <built-in function getitem>	
'b' (6570208)	function: <function b at 0x0318ED68>	
'Structure' (44804920)	type: <class 'impacket.structure.Structure'>	
'rand' (81532288)	SystemRandom: <random.SystemRandom object at 0x03E38028>	
'INADDR_ANY' (38905640)	str: 0.0.0.0	
'BROADCAST_ADDR' (76920136)	str: <broadcast>	
'NETBIOS_NS_PORT' (77628624)	int: 137	
'NETBIOS_SESSION_PORT' (77070208)	int: 139	
'SMB_SESSION_PORT' (77049728)	int: 445	
'NODE_B' (81532800)	int: 0	
'NODE_P' (81532864)	int: 8192	
'NODE_M' (81533216)	int: 16384	
'NODE_RESERVED' (76877976)	int: 24576	
'NODE_GROUP' (76878056)	int: 32768	
'NODE_UNIQUE' (76878216)	int: 0	
'TYPE_UNKNOWN' (76878096)	int: 1	
'TYPE_WORKSTATION' (81595808)	int: 0	
'TYPE_CLIENT' (76878296)	int: 3	
'TYPE_SERVER' (77526144)	int: 32	
'TYPE_DOMAIN_MASTER' (81595712)	int: 27	
'TYPE_DOMAIN_CONTROLLER' (81595568)	int: 28	
'TYPE_MASTER_BROWSER' (81594800)	int: 29	
'TYPE_BROWSER' (76878336)	int: 30	
'TYPE_NETDDE' (76878616)	int: 31	
'TYPE_STATUS' (76878696)	int: 33	
'OPCODE_QUERY' (76878656)	int: 0	
'OPCODE_REGISTRATION' (81594272)	int: 10240	
'OPCODE_RELEASE' (76879256)	int: 12288	
'OPCODE_WACK' (76878776)	int: 14336	
'OPCODE_REFRESH' (76878856)	int: 16384	
'OPCODE_REQUEST' (76878816)	int: 0	
'OPCODE_RESPONSE' (76880576)	int: 32768	
'NM_FLAGS_BROADCAST' (81593936)	int: 16	
'NM_FLAGS_UNICAST' (81593888)	int: 0	
'NM_FLAGS_RA' (76880536)	int: 128	
'NM_FLAGS_RD' (76877936)	int: 256	
'NM_FLAGS_TC' (76918600)	int: 512	
'NM_FLAGS_AA' (76918480)	int: 1024	
'QUESTION_TYPE_NB' (81593840)	int: 32	
'QUESTION_TYPE_NBSTAT' (81593744)	int: 33	
'QUESTION_CLASS_IN' (81593984)	int: 1	
'RR_TYPE_A' (76917800)	int: 1	
'RR_TYPE_NS' (76918320)	int: 2	
'RR_TYPE_NULL' (76917680)	int: 10	
'RR_TYPE_NB' (76917840)	int: 32	
'RR_TYPE_NBSTAT' (76918400)	int: 33	
'RR_CLASS_IN' (76917920)	int: 1	
'RCODE_FMT_ERR' (76918000)	int: 1	
'RCODE_SRV_ERR' (76917880)	int: 2	
'RCODE_IMP_ERR' (76918440)	int: 4	
'RCODE_RFS_ERR' (76918520)	int: 5	
'RCODE_ACT_ERR' (76918560)	int: 6	
'RCODE_CFT_ERR' (76918640)	int: 7	
'NAME_FLAGS_PRM' (76918680)	int: 512	
'NAME_FLAGS_ACT' (76918720)	int: 1024	
'NAME_FLAG_CNF' (76857280)	int: 2048	
'NAME_FLAG_DRG' (81319920)	int: 4096	
'NB_FLAGS_ONT_B' (81319880)	int: 0	
'NB_FLAGS_ONT_P' (81319840)	int: 8192	
'NB_FLAGS_ONT_M' (81319800)	int: 16384	
'NB_FLAGS_G' (81319760)	int: 32768	
'NAME_TYPES' (81319720)	dict: {1: 'Unknown', 0: 'Workstation', 3: 'Client', 32: 'Server', 27: 'Domain Master', 28: 'Domain Controller', 29: 'Master Browser', 30: 'Browser Server', 31: 'NetDDE Server', 33: 'Status'}	
'NETBIOS_SESSION_MESSAGE' (81593696)	int: 0	
'NETBIOS_SESSION_REQUEST' (81593504)	int: 129	
'NETBIOS_SESSION_POSITIVE_RESPONSE' (81314784)	int: 130	
'NETBIOS_SESSION_NEGATIVE_RESPONSE' (81314848)	int: 131	
'NETBIOS_SESSION_RETARGET_RESPONSE' (81314912)	int: 132	
'NETBIOS_SESSION_KEEP_ALIVE' (76853048)	int: 133	
'encode_name' (81318840)	function: <function encode_name at 0x0495D9C0>	
'_do_first_level_encoding' (81256536)	function: <function _do_first_level_encoding at 0x04964348>	
'decode_name' (81318120)	function: <function decode_name at 0x04964390>	
'_do_first_level_decoding' (81442480)	function: <function _do_first_level_decoding at 0x049643D8>	
'ERRCLASS_QUERY' (81319360)	int: 0	
'ERRCLASS_SESSION' (81593648)	int: 240	
'ERRCLASS_OS' (81319280)	int: 255	
'QUERY_ERRORS' (81319240)	dict: {1: 'Format Error. Request was invalidly formatted', 2: 'Server failure. Problem with NBNS, cannot process name.', 3: 'Name does not exist', 4: 'Unsupported request error.  Allowable only for challenging NBNS when gets an Update type registration request.', 5: 'Refused error.  For policy reasons server will not register this name from this host.', 6: 'Active error.  Name is owned by another node.', 7: 'Name in conflict error.  A UNIQUE name is owned by more than one node.'}	
'SESSION_ERRORS' (81319160)	dict: {128: 'Not listening on called name', 129: 'Not listening for calling name', 130: 'Called name not present', 131: 'Sufficient resources', 143: 'Unspecified error'}	
'NetBIOSError' (77526544)	type: <class 'impacket.nmb.NetBIOSError'>	
'NetBIOSTimeout' (81318920)	type: <class 'impacket.nmb.NetBIOSTimeout'>	
'NBNSResourceRecord' (81560208)	type: <class 'impacket.nmb.NBNSResourceRecord'>	
'NBNodeStatusResponse' (81560256)	type: <class 'impacket.nmb.NBNodeStatusResponse'>	
'NBPositiveNameQueryResponse' (76775680)	type: <class 'impacket.nmb.NBPositiveNameQueryResponse'>	
'NAME_SERVICE_PACKET' (81560304)	type: <class 'impacket.nmb.NAME_SERVICE_PACKET'>	
'QUESTION_ENTRY' (81246192)	type: <class 'impacket.nmb.QUESTION_ENTRY'>	
'RESOURCE_RECORD' (81245712)	type: <class 'impacket.nmb.RESOURCE_RECORD'>	
'NAME_REGISTRATION_REQUEST' (76775736)	type: <class 'impacket.nmb.NAME_REGISTRATION_REQUEST'>	
'NAME_OVERWRITE_REQUEST' (81560496)	type: <class 'impacket.nmb.NAME_OVERWRITE_REQUEST'>	
'NAME_REFRESH_REQUEST' (81560640)	type: <class 'impacket.nmb.NAME_REFRESH_REQUEST'>	
'NAME_REGISTRATION_RESPONSE' (76775904)	type: <class 'impacket.nmb.NAME_REGISTRATION_RESPONSE'>	
'NAME_CONFLICT_DEMAND' (81562704)	type: <class 'impacket.nmb.NAME_CONFLICT_DEMAND'>	
'NAME_QUERY_REQUEST' (81563088)	type: <class 'impacket.nmb.NAME_QUERY_REQUEST'>	
'ADDR_ENTRY' (81245472)	type: <class 'impacket.nmb.ADDR_ENTRY'>	
'NODE_STATUS_REQUEST' (81559584)	type: <class 'impacket.nmb.NODE_STATUS_REQUEST'>	
'NODE_NAME_ENTRY' (81248192)	type: <class 'impacket.nmb.NODE_NAME_ENTRY'>	
'STATISTICS' (81244712)	type: <class 'impacket.nmb.STATISTICS'>	
'NetBIOS' (76839648)	type: <class 'impacket.nmb.NetBIOS'>	
'NetBIOSSessionPacket' (81562752)	type: <class 'impacket.nmb.NetBIOSSessionPacket'>	
'NetBIOSSession' (81536328)	type: <class 'impacket.nmb.NetBIOSSession'>	
'NetBIOSUDPSessionPacket' (81563184)	type: <class 'impacket.nmb.NetBIOSUDPSessionPacket'>	
'NetBIOSUDPSession' (81560064)	type: <class 'impacket.nmb.NetBIOSUDPSession'>	
'NetBIOSTCPSession' (77036480)	type: <class 'impacket.nmb.NetBIOSTCPSession'>	
__len__	int: 122	


**Handling the exception on line 986, throws a new error: TypeError: 'ConnectionResetError' object is not subscriptable**
bottom-line, this code -- which tries to handle the ConnectionResetError -- cannot access the subscripts, and throws another exception:
986:                if ex[0] != errno.EINTR and ex[0] != errno.EAGAIN:

**Comment by pacmanoth** [comment] 2019-04-03 23:33
BTW, the ConnectionResetError does NOT occur when I run the latest version of impacket under Python 2.7

**Comment by pacmanoth** [comment] 2019-04-03 23:59
So, I guess there are 2 bugs here:
1) ConnectionResetError should not have occurred in the first place (it doesn't under Python 2.7)
2) When handling the ConnectionReserError, the code should not access the exception using sub-scripts

Hope this is helpful :-)

**Comment by asolino** [comment] 2019-05-07 16:35
Are you still experiencing this issue?

**Comment by idangur** [comment] 2019-05-14 12:32
I don't know about the creator of the issue, but I'm still experiencing this issue today.

**Comment by idangur** [comment] 2019-05-15 18:54
Hey alberto,

I'm currently not at work but i am using the 0.9.20 dev version with python
3.7.3.

For repro steps i can't help further today but will be happy to help
tommorow.

Thanks in forward, Idan.

**Comment by awsmhacks** [comment] 2019-08-06 19:00
Tested this in what I assume is a similar situation.    
  
@pacmanoth  and @idangur  I've experienced this when not using the proper smb version on the server.  
Try setting up the server with smb2 support enabled.  
  
 using setSMB2Support(true)   
or  
with in config ~  smbConfig.set("global", "SMB2Support", "True")

**Comment by awsmhacks** [comment] 2019-08-06 20:54
huzzah, think ive determined the issue. At least in my case. 
   
Used the following as a simple test:  
on kali linux  
`# smbserver.py -smb2support -debug TEST /tst`
  
on a win10 host    
`net use \\IP\TEST\tst ` 
Gives us the error
`"You cant access this shared folder because your organizations security policies block unauthenticated guest access"  `
And back on kali we see the ConnectionResetError Issue. (which also is showing up during the smbv1/v2 negotiation checks but thats a different issue)  

If we change the smbserver to require creds via -username and -password **it works!**
This might be default behavior on newer win10 or something the org has disabled manually.  
   
Suggest trying both enabling smbv2 support _and_ requiring credentials

**Comment by pjbgf** [comment] 2020-01-25 14:15
Had the same problem as @awsmhacks, more info can be found here:
https://support.microsoft.com/en-gb/help/4046019/guest-access-in-smb2-disabled-by-default-in-windows-10-and-windows-ser

**Comment by asolino** [comment] 2020-09-29 19:46
Looks like the issue is clarified and a workaround proposed. Closing.

**Closed by asolino** 2020-09-29 19:46 UTC
