### ISSUE TITLE
Bug in GetNPUsers.py TypeError: init() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by bLackCat-79** [SecureAuthCorp/impacket#800] opened 2020-03-19 18:53 UTC
### Configuration  
impacket version:  0.9.20
Python version:  2.7 3.6
Target OS:  windows 10

### Debug Output With Command String  
python GetNPUsers.py -usersfile users.txt -dc-ip 1.1.1.1  -no-pass -request -outputfile out somethin/
Impacket v0.9.20 - Copyright 2019 SecureAuth Corporation

Traceback (most recent call last):
  File "GetNPUsers.py", line 397, in <module>
    logger.init(options.ts)
TypeError: init() takes 0 positional arguments but 1 was given

And yes, I did pip install impacket and I ran python setup install

**Comment by anthorne** [comment] 2020-03-21 11:59
I had the same problem, but I solved it by downloading the latest version of impacket.
https://github.com/SecureAuthCorp/impacket

`kali@kali:~/tools$ git clone https://github.com/SecureAuthCorp/impacket.git
Cloning into 'impacket'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 17737 (delta 3), reused 3 (delta 0), pack-reused 17726
Receiving objects: 100% (17737/17737), 5.88 MiB | 8.55 MiB/s, done.
Resolving deltas: 100% (13549/13549), done.
kali@kali:~/tools$ cd impacket/
kali@kali:~/tools/impacket$ ls
ChangeLog  examples  impacket  LICENSE  MANIFEST.in  README.md  requirements.txt  setup.py  tests  tox.ini
kali@kali:~/tools/impacket$ pip install .
Processing /home/kali/tools/impacket
Requirement already satisfied: flask>=1.0 in /home/kali/.local/lib/python2.7/site-packages (from impacket==0.9.21.dev1+20200313.160519.0056b61c) (1.1.1)
Requirement already satisfied: ldap3!=2.5.0,!=2.5.2,!=2.6,>=2.5 in /home/kali/.local/lib/python2.7/site-packages (from impacket==0.9.21.dev1+20200313.160519.0056b61c) (2.5.1)
Requirement already satisfied: ldapdomaindump>=0.9.0 in /home/kali/.local/lib/python2.7/site-packages (from impacket==0.9.21.dev1+20200313.160519.0056b61c) (0.9.2)
Requirement already satisfied: pyOpenSSL>=0.13.1 in /usr/lib/python2.7/dist-packages (from impacket==0.9.21.dev1+20200313.160519.0056b61c) (19.0.0)
Requirement already satisfied: pyasn1>=0.2.3 in /home/kali/.local/lib/python2.7/site-packages (from impacket==0.9.21.dev1+20200313.160519.0056b61c) (0.4.8)
Requirement already satisfied: pycryptodomex in /home/kali/.local/lib/python2.7/site-packages (from impacket==0.9.21.dev1+20200313.160519.0056b61c) (3.9.7)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from impacket==0.9.21.dev1+20200313.160519.0056b61c) (1.14.0)
Requirement already satisfied: Jinja2>=2.10.1 in /home/kali/.local/lib/python2.7/site-packages (from flask>=1.0->impacket==0.9.21.dev1+20200313.160519.0056b61c) (2.11.1)
Requirement already satisfied: itsdangerous>=0.24 in /home/kali/.local/lib/python2.7/site-packages (from flask>=1.0->impacket==0.9.21.dev1+20200313.160519.0056b61c) (1.1.0)
Requirement already satisfied: Werkzeug>=0.15 in /home/kali/.local/lib/python2.7/site-packages (from flask>=1.0->impacket==0.9.21.dev1+20200313.160519.0056b61c) (1.0.0)
Requirement already satisfied: click>=5.1 in /home/kali/.local/lib/python2.7/site-packages (from flask>=1.0->impacket==0.9.21.dev1+20200313.160519.0056b61c) (7.1.1)
Requirement already satisfied: dnspython in /usr/lib/python2.7/dist-packages (from ldapdomaindump>=0.9.0->impacket==0.9.21.dev1+20200313.160519.0056b61c) (1.16.0)
Requirement already satisfied: future in /usr/lib/python2.7/dist-packages (from ldapdomaindump>=0.9.0->impacket==0.9.21.dev1+20200313.160519.0056b61c) (0.16.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/kali/.local/lib/python2.7/site-packages (from Jinja2>=2.10.1->flask>=1.0->impacket==0.9.21.dev1+20200313.160519.0056b61c) (1.1.1)
Building wheels for collected packages: impacket
  Running setup.py bdist_wheel for impacket ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-D3Z7q1/wheels/0b/66/3a/11c0f415c0faf328226dcf2c246ed0781b0fed1fe08508b156
Successfully built impacket
Installing collected packages: impacket
  Found existing installation: impacket 0.9.20
    Uninstalling impacket-0.9.20:
      Successfully uninstalled impacket-0.9.20
Successfully installed impacket-0.9.21.dev1+20200313.160519.0056b61c
`

Good luck!

**Comment by asolino** [comment] 2020-03-25 19:19
Closing as duplicate of #754

**Closed by asolino** 2020-03-25 19:19 UTC
