### ISSUE TITLE
smbserver.py error

### ISSUE THREAD

**Issue by socversity** [SecureAuthCorp/impacket#985] opened 2020-11-03 20:25 UTC
Hi, i've already installed "Impacket" tool previously. But today once i try to run smbserver.py, am receiving following error.

`$ smbserver.py 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (impacket 0.9.22.dev1 (/home/kali/.local/lib/python3.8/site-packages), Requirement.parse('impacket==0.9.22.dev1+20201015.130615.81eec85a'))

`
**Later on i try to fix it, i downloaded again Impacket and try to install it with "pip3 install ."
I receive following output.** 

`pip3 install .

Processing /home/kali/Downloads/impacket-master
Requirement already satisfied: flask>=1.0 in /usr/lib/python3/dist-packages (from impacket==0.9.22.dev1) (1.1.1)
Requirement already satisfied: ldap3!=2.5.0,!=2.5.2,!=2.6,>=2.5 in /usr/lib/python3/dist-packages (from impacket==0.9.22.dev1) (2.5.1)
Requirement already satisfied: ldapdomaindump>=0.9.0 in /usr/lib/python3/dist-packages (from impacket==0.9.22.dev1) (0.9.1)
Requirement already satisfied: pyOpenSSL>=0.13.1 in /usr/lib/python3/dist-packages (from impacket==0.9.22.dev1) (19.0.0)
Requirement already satisfied: pyasn1>=0.2.3 in /usr/lib/python3/dist-packages (from impacket==0.9.22.dev1) (0.4.2)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from impacket==0.9.22.dev1) (3.6.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from impacket==0.9.22.dev1) (1.14.0)
Building wheels for collected packages: impacket
  Building wheel for impacket (setup.py) ... done
  Created wheel for impacket: filename=impacket-0.9.22.dev1-py3-none-any.whl size=1377864 sha256=fe8ec98a76f77994c6d145ed623b23f2c70ff3d21c6575c56ed1b55a293b37a0
  Stored in directory: /home/kali/.cache/pip/wheels/ab/ae/ad/64596dc7c37b7e7c332a8aab9a3842c931d2ecbf64180c2935
Successfully built impacket
Installing collected packages: impacket
Successfully installed impacket-0.9.22.dev1
`

**after installation once i try to run smbserver.py, i receive same error like above.**

**Comment by reybango** [comment] 2020-11-04 21:42
I'm having the same issue after installing on the latest Kali 

Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux

Error message:
_smbserver.py 
Traceback (most recent call last):
  File "/usr/local/bin/smbserver.py", line 4, in <module>
    __import__('pkg_resources').run_script('impacket==0.9.22.dev1+20201015.130615.81eec85a', 'smbserver.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1434, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/smbserver.py' not found in metadata at '/usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20201015.130615.81eec85a.dist-info'_

I think this may be an issue with Kali because the python alias was broken and I couldn't run python until I created a new alias to python3. I'm suspecting there's a deeper issue in the Kali update.

**Comment by asolino** [comment] 2020-11-05 13:30
Hey @reybango, @socversity 

Can you confirm this is happening to you on Kali 2020.3? I'll be downloading and installing it today.
Did you test `impacket` installation under `virtualenv`? I want to rule out it's a library specific issue and more towards a Kali issue as @reybango pointed out.

**Comment by reybango** [comment] 2020-11-05 15:17
@asolino I'll test in the latest Kali and let you know. I also tested this out on Ubuntu 20.x LTS and the same thing happened. 

Note that Debian removed the 'python' symlink in there latest update. I'm not sure if that's related but wanted to mention it.

**Comment by asolino** [comment] 2020-11-05 15:28
Just ran some tests against [Kali 2020.3](https://cdimage.kali.org/kali-2020.3/kali-linux-2020.3-installer-amd64.iso). There are a few steps needed to install an `impacket dev` version:

1. Switch to `root` (`sudo -s`) if needed.
2. Uninstall Kali's `impacket` version ( `0.9.21`):
```
apt-get remove python3-impacket
```
Note this will remove other packages that depend on `impacket` (e.g. `patator`, `polenum`, etc).
3. Install `python3-pip` package:
```
apt-get install python3-pip
```
4. Clone `impacket`'s sources:
```
cd /tmp
mkdir git-sources
cd git-sources
git clone https://github.com/SecureAuthCorp/impacket.git
```
5. Install `dev` version from source using `pip3`:
```
cd impacket
pip3 install . 
``` 
6. Test it!
```
root@kali2020-3:~# cd
root@kali2020-3:~# smbserver.py tmp /tmp
Impacket v0.9.22.dev1+20201105.115159.da48cfe7 - Copyright 2020 SecureAuth Corporation

[*] Config file parsed
[*] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
[*] Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
[*] Config file parsed
[*] Config file parsed
[*] Config file parsed
```

**Comment by asolino** [comment] 2020-11-05 15:30
Hey @reybango 

Let me know if the aforementioned steps work for you. 

> Note that Debian removed the 'python' symlink in there latest update. I'm not sure if that's related but wanted to mention it.


What you mean the `python` symlink removed? `/usr/bin/python` does not exist?

**Comment by reybango** [comment] 2020-11-05 15:43
@asolino it does not. From https://wiki.debian.org/Python

> NOTE: Debian testing (bullseye) has removed the "python" package and the '/usr/bin/python' symlink due to the deprecation of Python 2. No packaged scripts should depend on the existence of '/usr/bin/python': if they do, that is a bug that should be reported to Debian. You can use the 'python-is-python3' or 'python-is-python2' packages to restore an appropriate '/usr/bin/python' symlink for third-party or legacy scripts.

**Comment by reybango** [comment] 2020-11-05 15:53
I think I narrowed the issue down:

If I install impacket like this, it returns the error below:

_sudo pip3 install ._

It works!

If I install impacket like this, it returns the error below:

_sudo pip3 install .
sudo python3 setup.py install

Error:

smbserver.py 
Traceback (most recent call last):
  File "/usr/local/bin/smbserver.py", line 4, in <module>
    __import__('pkg_resources').run_script('impacket==0.9.22.dev1+20201105.115159.da48cfe7', 'smbserver.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1434, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/smbserver.py' not found in metadata at '/usr/local/lib/python3.8/dist-packages/impacket-0.9.22.dev1+20201105.115159.da48cfe7.dist-info'_

**Comment by asolino** [comment] 2020-11-05 15:54
@reybango . It does on the Kali I just installed:
```
beto@kali2020-3:~$ ls -la /usr/bin/python
lrwxrwxrwx 1 root root 7 Nov 18  2019 /usr/bin/python -> python2
beto@kali2020-3:~$ 
```
In any case, I don't think what you're experiencing is related to that (as long as you have a Python 3.x version installed).

**Comment by reybango** [comment] 2020-11-05 15:58
@asolino I did a "sudo apt update && sudo apt -y full-upgrade" on an existing Kali VM and the python symlink is not there. This is what the Kali team recommends to keep their rolling releases up-to-date. And I did the same with an existing Ubuntu VM and the symlink was also gone. So it's not isolated to Kali. Perhaps it only happens on upgrades?

Installing 'python-is-python3' brought the symlink back.

**Comment by asolino** [comment] 2020-11-05 16:07
> Installing 'python-is-python3' brought the symlink back.

Great to know.. I'm following your upgrade steps as well. Thanks for pointing that out.

Didn't understand your previous comment, probably due to formatting. Did the installation and execution finally worked?

**Comment by reybango** [comment] 2020-11-05 16:09
Awesome and thank you for going through this. Regarding the Impacket install question, it's yes and no.

- If I install impacket like this, it returns the error below:

_sudo pip3 install ._

smbserver.py works!

- If I install impacket like this, it returns the error below:

_sudo pip3 install .
sudo python3 setup.py install_

Then smbserver.py will throw errors.

**Comment by asolino** [comment] 2020-11-05 16:24
> * If I install impacket on Kali or Ubuntu like this, smbserver.py will throw errors.:
> 
> > _sudo pip3 install .
> > sudo python3 setup.py install_

Ohh  I see.. I will check that out trying to reproduce that issue, but you're basically using two different methods for installing the library in a row. That will probably install two copies under different directories (not sure about the latest Linux versions but that used to happen) or some other related incompatibilities. That's why we *just* mention in the [installation intructions](https://github.com/SecureAuthCorp/impacket/blob/master/README.md#quick-start) to use `pip/pip3` approach.

@reybango, based on your feedback looks like the installation is now working for you.. please confirm and I'll close this issue. Thanks!

**Comment by reybango** [comment] 2020-11-05 16:26
Thank you for letting me know @asolino. At this moment smbserver.py seems to be working using the install method you mentioned. 

I hope this thread was helpful. :)

**Comment by asolino** [comment] 2020-11-05 16:28
Thanks for the quick confirmation @reybango! I'm sure this will help others facing similar issues. Hope you enjoy `impacket` :). Closing.

**Closed by asolino** 2020-11-05 16:28 UTC

**Comment by reybango** [comment] 2020-11-05 16:30
@asolino one thing to note is that I've previously installed Impacket using the method below and it would work:

> sudo pip3 install .
> sudo python3 setup.py install

So something changed. Might be worth digging into it further if you have some cycles.

And yes, I can't imagine not using impacket. What an absolutely amazing tool you all have created. <3

**Comment by asolino** [comment] 2020-11-05 16:32
> So something changed. Might be worth digging into it further if you have some cycles.

Will certainly look into it.. thanks again for pointing it out!

**Comment by reybango** [comment] 2020-11-05 16:34
Muchisimas gracias @asolino!! :)

**Comment by servanh** [comment] 2024-02-26 21:17
> Just ran some tests against [Kali 2020.3](https://cdimage.kali.org/kali-2020.3/kali-linux-2020.3-installer-amd64.iso). There are a few steps needed to install an `impacket dev` version:
> 
>     1. Switch to `root` (`sudo -s`) if needed.
> 
>     2. Uninstall Kali's `impacket` version ( `0.9.21`):
> 
> 
> ```
> apt-get remove python3-impacket
> ```
> 
> Note this will remove other packages that depend on `impacket` (e.g. `patator`, `polenum`, etc). 3. Install `python3-pip` package:
> 
> ```
> apt-get install python3-pip
> ```
> 
>     4. Clone `impacket`'s sources:
> 
> 
> ```
> cd /tmp
> mkdir git-sources
> cd git-sources
> git clone https://github.com/SecureAuthCorp/impacket.git
> ```
> 
>     5. Install `dev` version from source using `pip3`:
> 
> 
> ```
> cd impacket
> pip3 install . 
> ```
> 
>     6. Test it!
> 
> 
> ```
> root@kali2020-3:~# cd
> root@kali2020-3:~# smbserver.py tmp /tmp
> Impacket v0.9.22.dev1+20201105.115159.da48cfe7 - Copyright 2020 SecureAuth Corporation
> 
> [*] Config file parsed
> [*] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
> [*] Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
> [*] Config file parsed
> [*] Config file parsed
> [*] Config file parsed
> ```

Just updating this thread to say this worked for me on Kali 2024.
