### ISSUE TITLE
Impossible to find Pek-List attribute in ntds file

### ISSUE THREAD

**Issue by quentinhardy** [SecureAuthCorp/impacket#456] opened 2018-05-21 14:26 UTC
Hello,

I am trying to use _secretsdump.py_ for extracting hashes from a big _ntds.dit_ file which has been copied with _vssadmin_.

When I run _secretsdump.py_, it seems **the script doesn't find the Pek-List attribute**:
```
Impacket v0.9.17-dev - Copyright 2002-2018 Core Security Technologies

[*] Target system bootKey: 0x****************************
[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Searching for pekList, be patient
[-] Error while calling getNextRow(), trying the next one
[-] Error while calling getNextRow(), trying the next one
[-] Error while calling getNextRow(), trying the next one
[-] Error while calling getNextRow(), trying the next one
[-] Error while calling getNextRow(), trying the next one
[-] Error while calling getNextRow(), trying the next one
[...]
Killed
```
This attribute is required for decrypting hashes.

I have the same bug with _impdump_ project (https://github.com/HarmJ0y/ImpDump/issues/5) wich uses the _impacket_ project (e.g. _esentutl.py_).

Notice **esedbexport** is running on this same ntds file (from some days) and there is an "ATTk590689" (Pek-List) attribute in database file (_database.4_ file). It is not finish but if I take this "ATTk590689" value from database.4 file and I use it directly in source code of https://github.com/HarmJ0y/ImpDump/blob/master/impdump.py, **it works**! : I can extract decrypted hashes.

So I think it is a bug in impacket -:(

Do you known if it a well known problem?

Thanks in advance for your help,

**Comment by asolino** [comment] 2018-05-23 17:39
Hey @quentinhardy 

First time I hear about this issue. 

According to your tests, looks like there's a bug in the [getNextRow()](https://github.com/CoreSecurity/impacket/blob/master/impacket/ese.py#L791) code. 

Now, without a way to reproduce this bug, it is almost imposible to determine where the problem is (in particular due to the complexity of the ESE format). Can you provide the DIT and registry hives to reproduce it?

If not, another alternative is for you to figure out where the problem is.

thanks,

**Comment by quentinhardy** [comment] 2018-05-25 21:26
Hello,

Unfortunately, I can't send you the ntds.dit file with the SYSTEM file.

I will try to search the problem.

**Comment by asolino** [comment] 2018-10-25 18:48
Should be fixed in https://github.com/SecureAuthCorp/impacket/commit/9efa50fe55a2aa1d6fa06d3f5a4d729f388b39aa

**Closed by asolino** 2018-10-25 18:48 UTC
