### ISSUE TITLE
WMIexec rpc_s access despite RPC serrvice running on host. 

### ISSUE THREAD

**Issue by Krack-1n** [SecureAuthCorp/impacket#661] opened 2019-08-01 22:36 UTC
I am trying to use wmiexec.py on a Windows 10 Home Version 10.0.17134 Build 17134 using my Kali version 4.19.0-kali3-amd64 but everytime I run the command I get this output. `python wmiexec.py DOMAIN/User:Password@IP
Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation

[*] SMBv3.0 dialect used
[-] rpc_s_access_denied` 
Any idea why this is happening despite RPC running on the target system?

**Comment by awsmhacks** [comment] 2019-09-02 22:26
It sounds like you might be testing on a non-domain joined machine?
You'll need to set the key to disable Remote UAC which is a default unless a computer has been joined to a domain.   
(You should check even if joined to a domain just in case)  
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\LocalAccountTokenFilterPolicy 

This article describes the probable situation and how to enable the key. https://support.pdq.com/knowledge-base/1055

A quick check to verify this is indeed the issue is by trying to mount the admin$ share from a different computer.
net use \\IP\ADMIN$ /user:username password
Will throw an error if Remote UAC is still enabled.

**Comment by asolino** [comment] 2019-09-10 18:28
Did you check @awsmhacks comments out @Krack-1n?

**Comment by 0xdeaddood** [comment] 2021-04-21 17:45
No answer, closing.

**Closed by 0xdeaddood** 2021-04-21 17:45 UTC
