### ISSUE TITLE
Request for version

### ISSUE THREAD

**Issue by nitzanbueno** [SecureAuthCorp/impacket#977] opened 2020-10-22 20:58 UTC
Hi!
I use the LDAP feature in impacket, and there's a bug with paging in the most recent version, that I later saw was already fixed on master.

I would like to use that bugfix, so it'll be nice if I could install it from pip.

Could you release a new version from master soon?

**Comment by asolino** [comment] 2020-11-05 14:04
Duplicate of https://github.com/SecureAuthCorp/impacket/issues/952

**Closed by asolino** 2020-11-05 14:04 UTC
